name: autofix.ci
on:
  pull_request:
    paths:
      - "poetry.lock"
      - "pyproject.toml"
      - "src/backend/**"
env:
  POETRY_VERSION: "1.8.2"

jobs:
  lint:
    name: Run Ruff Check and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: install-pinned/ruff@637d0ef041ff3ff0540a6d8d2092b0129babd5ec
      - run: ruff check --fix-only .
      - run: ruff format .
      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
